# Generated by Django 4.1.7 on 2023-04-06 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=40)),
                ('fecha_estreno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2023)])),
                ('reseña_pelicula', models.CharField(max_length=800)),
                ('valoracion_final', models.CharField(max_length=50)),
            ],
        ),
    ]
