# Generated by Django 4.1.7 on 2023-04-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculeando', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='año_estreno',
            new_name='año_estreno',
        ),
    ]
