# Generated by Django 4.1.7 on 2023-04-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Peliculeando', '0002_rename_fecha_estreno_post_año_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autorizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='autorizado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
