# Generated by Django 4.1.7 on 2023-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculeando', '0008_alter_post_imagen_alter_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pelicula_preferida',
            field=models.CharField(default='Volver al futuro', max_length=100),
            preserve_default=False,
        ),
    ]
