# Generated by Django 4.1.7 on 2023-04-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculeando', '0011_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reseña_pelicula',
            field=models.TextField(max_length=800),
        ),
    ]
