# Generated by Django 4.1.7 on 2023-04-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculeando', '0012_alter_post_reseña_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='titulo',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
